server:
  port: '8082'

spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Ullasmax@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Welcome to Swish!"'

---

spring:
  profiles:
    active: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: Ullasmax@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: '"Welcome to Swish!"'

management:
  endpoints:
    web:
      exposure:
        include: "*"

